---
- name: Include prerequisite packages
  ansible.builtin.include_tasks: prereqs.yml

- name: Check whether OpenVox GUI is already installed
  ansible.builtin.stat:
    path: "{{ openvox_gui_install_dir }}/VERSION"
  register: openvox_gui_already_installed

- name: Include OpenVox GUI installation
  ansible.builtin.include_tasks: install.yml
  when: not openvox_gui_already_installed.stat.exists
