---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: halif.openvox_gui
      vars:
        openvox_gui_version: "main"
        openvox_gui_puppetdb_host: "puppetdb.test.local"
        openvox_gui_puppet_server_host: "puppet.test.local"
        openvox_gui_auth_backend: "local"
        openvox_gui_debug: true
